package Constants;

public class Constants {
    /**
     * We use these 120 users for advanced analyze
     */
    public static final String lucky120 = "9ridesshotgun\n" +
            "abcnewsdarwin\n" +
            "adysadysan\n" +
            "albinusm\n" +
            "aloudhendo\n" +
            "analyzinglife\n" +
            "anna_frew\n" +
            "arii2010\n" +
            "ateegarden\n" +
            "baaheeyaah\n" +
            "bbum\n" +
            "bernardnio\n" +
            "binkyrocka85\n" +
            "bmitch4\n" +
            "brassyapple\n" +
            "brxxklynkay\n" +
            "calebmylove\n" +
            "carriebelles\n" +
            "ch3rylc\n" +
            "chickenguru\n" +
            "cikdotmon3y\n" +
            "cocktail_kitten\n" +
            "courtney358\n" +
            "customkids\n" +
            "danidocrafty\n" +
            "davidaprice\n" +
            "deepashah\n" +
            "dheedeye\n" +
            "djblaze2007\n" +
            "domynoe\n" +
            "drummerdaag\n" +
            "ecualibrium\n" +
            "elmoluvr21\n" +
            "ericsiebert\n" +
            "eyespypro\n" +
            "feferang\n" +
            "flowcoachbert\n" +
            "freeliving09\n" +
            "gajeebo\n" +
            "gexxinknox\n" +
            "gofigure11\n" +
            "groundreport\n" +
            "harbourexchange\n" +
            "herbalife_web\n" +
            "homeloanshub\n" +
            "iamangee\n" +
            "iheartth\n" +
            "infil00p\n" +
            "it_headlines\n" +
            "jacksonhybrid\n" +
            "jasonbierce\n" +
            "jeffnabers\n" +
            "jetaunelysse\n" +
            "jodi_ice\n" +
            "jordansfavgurl5\n" +
            "julietims\n" +
            "kaops19852\n" +
            "kcoopfly\n" +
            "kiamurphy\n" +
            "klim0824\n" +
            "kumaboo\n" +
            "laputean\n" +
            "legalize_gay\n" +
            "lilith_devas\n" +
            "lizzybusiness\n" +
            "lovenmarriage\n" +
            "m0del_chick\n" +
            "mambodejuliana\n" +
            "markmilly\n" +
            "maxsearchengine\n" +
            "melissatv\n" +
            "micole999\n" +
            "miserylovesco\n" +
            "mizzpeach410\n" +
            "monsterclimber\n" +
            "mrsdana\n" +
            "munkeycop\n" +
            "nabilagardena\n" +
            "nedranicole\n" +
            "nickjames_bitch\n" +
            "nofairdoctrine\n" +
            "obsessive_much\n" +
            "only1dmplz\n" +
            "pamteran\n" +
            "pechiyon\n" +
            "pikahsso\n" +
            "portafoliocomco\n" +
            "pruebear369\n" +
            "raastah\n" +
            "rawfoodnation\n" +
            "relenaa\n" +
            "rikafarah\n" +
            "roguegovernment\n" +
            "ruwthigh\n" +
            "samwinchester83\n" +
            "schoki3\n" +
            "seth_leitman\n" +
            "sheilasalsabela\n" +
            "silviostefano\n" +
            "slpadillag\n" +
            "sophie_jonas\n" +
            "stacie2287\n" +
            "stoop_uk\n" +
            "surrealistical\n" +
            "taktakchannel\n" +
            "teamkimberly\n" +
            "thatsmalayalam\n" +
            "thekoolguy\n" +
            "thighmanrocks\n" +
            "tizzygagablank\n" +
            "toshi03\n" +
            "tshaylag\n" +
            "tyronevh\n" +
            "valerieisbadd\n" +
            "vintagecardfun\n" +
            "wayoutmind\n" +
            "wilaysha12\n" +
            "wvterry\n" +
            "yahoocaent\n" +
            "yummin3ss";
}
